GET http://localhost:3000/api/books

###

GET http://localhost:3000/api/books/Dune Messiah

###

POST http://localhost:3000/api/books

###

PUT http://localhost:3000/api/books/734532563
Content-Type: application/json

{
    "title": "Dune Messiah",
    "author": "Frank Herbert",
    "price": 459
}

###

DELETE http://localhost:3000/api/books/41252134